### ISSUE TITLE
http and https

### ISSUE THREAD

**Issue by robert-mygind** [wifidog/wifidog-gateway#21]
Thanks for wifidog, it works perfect. I just have a little problem.

http gets redirected to the login page as it should but not https. I know that with https there are problems with man in the middle, but is it not possible just to have a iptables rule that "forwards" the request to another url, I don't need any info on the original request, post parameters or other things, just a redirect. Seems like it should be possible or ?

**Comment by acv** [comment]
Part of the issue with HTTPS is that you don't and can't know the domain name the user is connecting to. You can guess by correlating DNS lookup (and lose to DNS caches) or by reverse DNS but the only place where it's accurately reflected is in the `Host:` header inside that HTTPS connection.

MITM, while possible will yield certificate failures and big nasty security warnings since the certificate verification will fail. We have no way to compel the users to load our own CA root and in the case of `HSTS` using HTTPS sites, the browser will flag us anyway.

It's down to the browser/OS to detect that it's behind a captive portal and interface with it accordingly.
