### ISSUE TITLE
https:// url requests are not being redirected, not being captured by wifidog

### ISSUE THREAD

**Issue by laapsaap** [wifidog/wifidog-gateway#6]
Hi.

I spent hours on this one, stracing and reading the code but I cant see what is wrong.

I have wifidog all setup and working, when I type in http://etc.  I get redirected to the login page. And in debug mode I see it being captured -> Captured 192.168.1.109 requesting..etc.

But https://etc isnt doing anything, it times out after awhile in the browser. Nothing happens in debug mode.

Somehow wifidog is not triggered to http_callback_404.  I have no idea what is wrong and google doesnt find me anything about this.

Thank you very much!

Best regards,

**Comment by agustindev** [comment]
How?

**Comment by gareth41** [comment]
I wouldn't worry too much about redirecting https requests, the majority of devices, if not all these days seem to automatically detect the presence of a captive portal and bring up the login webpage anyway.  All iOS, Android, and Win 8/10 devices that i've come across do this, Win7 displays a message in bottom left corner saying "more information may be required to join network".  Therefore I don't think its an issue not being able to capture https requests. The exception would be older devices eg Win XP which is now obsolete anyway.  I did implement Libmicrohttpd into wifidog last year for testing a replacement to the Hughes Technology libhttpd which is ancient and not been updated for many many years since 2005 I think, Libmicrohttpd works fine with the only problem the wifidog executable increases in size which is a problem for devices with limited flash like some tp link ap's and the good old wrt54g.

**Comment by rakesh2215** [comment]
Hi Folks,
Have you looked at this?
https://github.com/liudf0716/apfree_wifidog
They are claiming https support. Any comments are welcome. I am yet to try this out myself.
