### ISSUE TITLE
Talk SSL to the auth server

### ISSUE THREAD

**Issue by mhaas** [wifidog/wifidog-gateway#61]
My auth server *only* talks HTTPS. Right now, I use stunnel in client mode to tunnel the connection. This pulls in quite a lot of dependencies.

My feature request/RFC: hook up a small SSL library like PolarSSL or the smaller cyassl. This could be  enabled on compile time. Hooking up [cyassl is quite straightforward](http://www.yassl.com/yaSSL/Docs-cyassl-manual-3-getting-started.html).

Would there be interest in such a feature? Any ideas on that?

**Comment by acv** [comment]
It should probably be configurable (default: on) via the configure script. It was rejected initially because of space/performance constraint on the lower end WRT54Gs, 2MB flash and 8MB ram plus the very limited CPU was insufficient to support SSL.

Certificate validation rules can be an issue with TLS. Library should also support TLS v1.2, forward secure cipher suites (e.g. ECDHE) and modern AEAD ci[her modes (i.e.: AES-GCM).

**Comment by acv** [comment]
Looks like cyassl generally meets the requirements I said.

**Comment by sinkcup** [comment]
I suggest to show two choices in openwrt menuconfig, wifidog and wifidog-xxxssl, if choose wifidog-xxxssl, it depends ssl when opkg install, else don't depends.
like this: https://github.com/shadowsocks/openwrt-shadowsocks
![2015-03-13 14 38 30](https://cloud.githubusercontent.com/assets/4971414/6634153/a782c144-c98e-11e4-95ec-8fb9e87fdbe9.png)

**Comment by mhaas** [comment]
I already have that. I will upload it soon.

Am 13. März 2015 07:39:04 MEZ, schrieb sinkcup <notifications@github.com>:
